version: '3.7'

services:
  votingbuck-frontend:
    image: votingbuck-frontend_server
    build:
      context: .
    ports:
      - 80:80 
      - 443:443
    volumes:
      - ./.env:/.env
      - /etc/letsencrypt/:/etc/letsencrypt/