version: '3.3'

services:
  4470_frontend_container:
    container_name: "4470-frontend-container"
    build: .
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true