version: '3.7'

services:
  votingbuck-frontend:
    image: 549369157589.dkr.ecr.us-east-2.amazonaws.com/votingbuck-frontend_server
    build:
      context: .
    ports:
      - 80:80 
      - 443:443
    volumes:
      - ./.env:/.env
      - /home/ec2-user/.votingbuck/certs/:/home/ec2-user/.votingbuck/certs/
      - /etc/letsencrypt/:/etc/letsencrypt/